#!/usr/bin/env bash

set -e


ALL_PHASES="network storage compute build"
ALL_ENVS="dev test int prod"

DEFAULT_ENVIRONMENT=dev

# --------------------------------------------------------------------------------------------------
# PREPARE
# --------------------------------------------------------------------------------------------------

TWRAP_CONFIG_FILE=".clouduct-tf"

# ensure we're executing in the correct directory
SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
cd "${SCRIPT_DIR}"

BASENAME=$(basename "$0")

# check for existence of config file
if [ -e "$TWRAP_CONFIG_FILE" ]; then
  source "${TWRAP_CONFIG_FILE}"
else
  echo "Could not find configuration file ${TWRAP_CONFIG_FILE}"
  exit 1
fi

if [[ -z $TF_VAR_project_name ]]; then
  echo "missing environment variable TF_VAR_project_name"
  echo "should have been set in $TWRAP_CONFIG_FILE"
  exit 1
fi

if [[ -z $TF_VAR_region ]]; then
  echo "missing environment variable TF_VAR_region"
  echo "should have been set in $TWRAP_CONFIG_FILE"
  exit 1
fi


ALL_PHASES_ALT="${ALL_PHASES// /|}"
ALL_ENVS_ALT="${ALL_ENVS// /|}"

usage() {
  echo "Usage:"
  echo "  ${BASENAME} [env] [phase] [command]"
  echo "  "
  echo "     env           ${ALL_ENVS_ALT} -- default: dev"
  echo "     phase         ${ALL_PHASES_ALT} -- if omitted all phases will be executed"
  echo "     command       plan|apply|destroy ('bootstrap' can only be called once) -- default: plan"
  echo "  "
}

trim() {
  echo "$*" | sed -e 's/ $//' -e 's/^ //'
}

contains() {
  local item="$1"
  local list="$2"

  if [[ " $list " =~ " $item " ]]; then
    return 0
  else
    return 1
  fi
}

# allow to use the variable as match against possible command line arguments:
shopt -s extglob
ALL_PHASES_TEST="+($ALL_PHASES_ALT)"
ALL_ENVS_TEST="+($ALL_ENVS_ALT)"

if contains "$1" "$ALL_ENVS" ; then
  TF_VAR_environment="$1"
  shift
elif [[ -z $TF_VAR_environment ]]; then
  TF_VAR_environment="$DEFAULT_ENVIRONMENT"
fi

while contains "$1" "$ALL_PHASES"; do
  PHASES="$1 $PHASES"
  shift
done

if contains "$1" "bootstrap plan apply destroy"; then
  terraform_command="$1"
  shift
fi

if [[ "$1" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -gt 0 ]]; then
  echo "unknown parameter(s) $*"
  echo
  usage
  exit 1
fi

# default command: plan
terraform_command=${terraform_command:-plan}

if [[ "${PHASES}" = "" ]]; then
  PHASES_IN_EXEC_ORDER=$ALL_PHASES
else
  # ensure the phasess are in the correct order
  PHASES=$(echo "$PHASES" | sed -e 's/ $//' -e 's/ /\|/')
  for phase in $ALL_PHASES; do
    if [[ $phase =~ .*${PHASES}.* ]]; then
      PHASES_IN_EXEC_ORDER="$PHASES_IN_EXEC_ORDER $phase"
    fi
  done
fi

PHASES_IN_EXEC_ORDER=$(trim $PHASES_IN_EXEC_ORDER)

echo "$TF_VAR_project_name env: ($TF_VAR_environment) phases: ($PHASES_IN_EXEC_ORDER) command: ($terraform_command)"

# # ensure if the NAME-infra directory exists:
# INFRA_DIR="${CLOUDUCT_PROJECTNAME}-infra"
# if [ ! -d "${INFRA_DIR}" ]; then
#   echo "could not find directory ${INFRA_DIR}"
#   exit 2
# fi

INFRA_DIR="$( cd "$( dirname "$0" )" && pwd )"

# --------------------------------------------------------------------------------------------------
# EXECUTE
# --------------------------------------------------------------------------------------------------

for phase in ${PHASES_IN_EXEC_ORDER}; do
  # echo "${INFRA_DIR}/$phase"
  pushd "${INFRA_DIR}/$phase" > /dev/null

  BUCKET="${TF_VAR_project_name}-infra-${TF_VAR_environment}-remote-state-bucket"

  terraform init -reconfigure \
    -backend-config="region=${TF_VAR_region}" \
    -backend-config="bucket=${BUCKET}" \
    -backend-config="key=${phase}"

  terraform "${terraform_command}"

  popd > /dev/null

done

exit 0

