#!/usr/bin/env bash

set -e


ALL_PHASES="network storage compute build"
ALL_ENVS="dev test int prod"

# --------------------------------------------------------------------------------------------------
# PREPARE
# --------------------------------------------------------------------------------------------------

TWRAP_CONFIG_FILE=".twrap"

# ensure we're executing in the correct directory
SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
cd "${SCRIPT_DIR}"

BASENAME=$(basename "$0")

# check for existence of config file
if [ -e "$TWRAP_CONFIG_FILE" ]; then
  source "${TWRAP_CONFIG_FILE}"
else
  echo "Could not find configuration file ${TWRAP_CONFIG_FILE}"
  exit 1
fi

if [[ -z $CLOUDUCT_PROJECTNAME ]]; then
  echo "missing environment variable CLOUDUCT_PROJECTNAME"
  echo "should have been set in $TWRAP_CONFIG_FILE"
  exit 1
fi

if [[ -z $CLOUDUCT_REGION ]]; then
  echo "missing environment variable CLOUDUCT_REGION"
  echo "should have been set in $TWRAP_CONFIG_FILE"
  exit 1
fi


ALL_PHASES_ALT="${ALL_PHASES// /|}"
ALL_ENVS_ALT="${ALL_ENVS// /|}"

usage() {
  echo "Usage:"
  echo "  ${BASENAME} [env] [phase] [command]"
  echo "  "
  echo "     env           ${ALL_ENVS_ALT} -- default: dev"
  echo "     phase         ${ALL_PHASES_ALT} -- if omitted all phases will be executed"
  echo "     command       plan|apply|destroy ('bootstrap' can only be called once) -- default: plan"
  echo "  "
}

trim() {
  echo "$*" | sed -e 's/ $//' -e 's/^ //'
}

contains() {
  local item="$1"
  local list="$2"

  if [[ " $list " =~ " $item " ]]; then
    return 0
  else
    return 1
  fi
}

# allow to use the variable as match against possible command line arguments:
shopt -s extglob
ALL_PHASES_TEST="+($ALL_PHASES_ALT)"
ALL_ENVS_TEST="+($ALL_ENVS_ALT)"

if contains "$1" "$ALL_ENVS" ; then
  ENVIRONMENT="$1"
  shift
fi

while contains "$1" "$ALL_PHASES"; do
  PHASES="$1 $PHASES"
  shift
done

if contains "$1" "bootstrap plan apply destroy"; then
  terraform_command="$1"
  shift
fi

if [[ "$1" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -gt 0 ]]; then 
  echo "unknown parameter(s) $*"
  echo
  usage
  exit 1
fi

# default command: plan
terraform_command=${terraform_command:-plan}

if [[ "${PHASES}" = "" ]]; then
  PHASES_IN_EXEC_ORDER=$ALL_PHASES
else
  # ensure the phasess are in the correct order
  PHASES=$(echo "$PHASES" | sed -e 's/ $//' -e 's/ /\|/')
  for phase in $ALL_PHASES; do
    if [[ $phase =~ .*${PHASES}.* ]]; then
      PHASES_IN_EXEC_ORDER="$PHASES_IN_EXEC_ORDER $phase"
    fi
  done
fi

PHASES_IN_EXEC_ORDER=$(trim $PHASES_IN_EXEC_ORDER)

echo "$CLOUDUCT_PROJECTNAME env: ($ENVIRONMENT) phases: ($PHASES_IN_EXEC_ORDER) command: ($terraform_command)"

# ensure if the NAME-infra directory exists:
INFRA_DIR="${CLOUDUCT_PROJECTNAME}-infra"
if [ ! -d "${INFRA_DIR}" ]; then
  echo "could not find directory ${INFRA_DIR}"
  exit 2
fi

# --------------------------------------------------------------------------------------------------
# EXECUTE
# --------------------------------------------------------------------------------------------------

# TODO INTERMEDIATE_DIR="terrorform"

for phase in ${PHASES_IN_EXEC_ORDER}; do
  echo "${INFRA_DIR}/$phase"
  pushd "${INFRA_DIR}/$phase" > /dev/null

  # terraform get

  # if [[ "${terraform_command}" ==  'bootstrap' ]]; then
  #   terraform init \
  #       -backend-config "project_name=${CLOUDUCT_PROJECTNAME}" \
  #       -backend-config "environment=${ENVIRONMENT}" \
  #       -backend-config "region=${region}"
  # else
  #   terraform "${terraform_command}" \
  #       -var "project_name=${CLOUDUCT_PROJECTNAME}" \
  #       -var "environment=${environment}" \
  #       -var "region=${region}"
  # fi

  popd > /dev/null

done

exit 0

